### ISSUE TITLE
Feature: Expression evaluation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mlieshoff/exactor#27]
```
It will be very cool if we had some kind of expression evaluation in variable 
values.
```

Original issue reported on code.google.com by `michael....@gmail.com` on 7 Aug 2013 at 9:03

**Comment by mlieshoff** [comment]
done

**Comment by eeijlar** [comment]
Hi Michael,

When is the next release of exactor? The expression evaluation would be a
very useful feature for us.

Regards,
John

**Comment by mlieshoff** [comment]
Hi John. We plan it asap for the 1.1.30, in one of the first snapshots we release under 1.1.30.XXXXXXX. I'll inform you the next days.

Best regards, 
Michael

**Comment by mlieshoff** [comment]
We would use JEXL for the expression evaluation and expressions are encapsulated in {} for variables in commands.

**Comment by mlieshoff** [comment]
Hi John, please check out the 1.1.30.100215 (https://github.com/mlieshoff/exactor/blob/wiki/HowToUseInMaven.md) for the latest expression changes. It works on all parameters, annotated or not and use the JEXL (https://commons.apache.org/proper/commons-jexl/reference/syntax.html)  syntax for expressions encapsulated in braces.

Example: MyFooCommand value={40+2} 

Result will be value=42 in commands attribute. Variables used in JEXL's MapContext will comming later.

**Comment by ykleong** [comment]
Hi Michael.

Great stuff!
Was just wondering if it would work with substitutions like this ?
MyFooCommand value={[startValue]+2}

**Comment by eeijlar** [comment]
Great - thanks Michael, we have pulled down the 1.1.30.100215 release

**Comment by eeijlar** [comment]
Hi Michael, we are using the JEXL expressions - they are really great! Good feeback from everyone on them.

**Comment by mlieshoff** [comment]
Thank you very much :)
